USE [master]
GO

/****** Object:  Database [EBookstore]    Script Date: 20-03-2025 14:21:53 ******/
CREATE DATABASE [EBookstore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EBookstore', FILENAME = N'D:\Apps\MSSQL16.SQLEXPRESS\MSSQL\DATA\EBookstore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EBookstore_log', FILENAME = N'D:\Apps\MSSQL16.SQLEXPRESS\MSSQL\DATA\EBookstore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EBookstore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EBookstore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EBookstore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EBookstore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EBookstore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EBookstore] SET ARITHABORT OFF 
GO

ALTER DATABASE [EBookstore] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EBookstore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EBookstore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EBookstore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EBookstore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EBookstore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EBookstore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EBookstore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EBookstore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EBookstore] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EBookstore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EBookstore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EBookstore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EBookstore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EBookstore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EBookstore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EBookstore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EBookstore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EBookstore] SET  MULTI_USER 
GO

ALTER DATABASE [EBookstore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EBookstore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EBookstore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EBookstore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EBookstore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EBookstore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EBookstore] SET QUERY_STORE = ON
GO

ALTER DATABASE [EBookstore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EBookstore] SET  READ_WRITE 
GO

